services:
  poc-fos-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: poc-fos-development:latest
    container_name: poc-fos-development
    ports:
      - "${HOST_PORT:-3001}:80"
    restart: unless-stopped
